# -*- coding: utf-8 -*-
"""
Pydantic v2 schemas - 02水生生态. Auto-generated by tools/build_schema.py.
"""
from datetime import datetime
from decimal import Decimal
from typing import Optional
from pydantic import BaseModel, ConfigDict

class HabitatMonitorDataCreate(BaseModel):
    """Create payload for 生境监测数据表"""

    monitor_code: str
    eco_code: Optional[str] = None
    eco_name: Optional[str] = None
    ecogklocation: Optional[str] = None
    ecogkbrief: Optional[str] = None
    monitor_time: Optional[datetime] = None
    dzlxbrief: Optional[str] = None
    dztzbrief: Optional[str] = None
    hedu_eco: Optional[str] = None
    dox: Optional[Decimal] = None
    wgbh: Optional[Decimal] = None
    cond: Optional[Decimal] = None
    ph: Optional[Decimal] = None
    wyyzk: Optional[str] = None
    yd: Optional[Decimal] = None
    wq: Optional[Decimal] = None
    wtemp: Optional[Decimal] = None
    wv: Optional[Decimal] = None
    wtmd: Optional[Decimal] = None
    wzb: Optional[str] = None
    rvltpj: Optional[str] = None
    wlong: Optional[Decimal] = None
    wwidth: Optional[Decimal] = None
    wdepth: Optional[Decimal] = None
    warea: Optional[Decimal] = None
    yatzh: Optional[str] = None
    hctzh: Optional[str] = None
    zrrkzg: Optional[str] = None
    gytd: Optional[str] = None
    pazbdyx: Optional[str] = None
    abtdlylx: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class HabitatMonitorData(BaseModel):
    """Read model for 生境监测数据表"""
    model_config = ConfigDict(from_attributes=True)

    monitor_code: Optional[str] = None
    eco_code: Optional[str] = None
    eco_name: Optional[str] = None
    ecogklocation: Optional[str] = None
    ecogkbrief: Optional[str] = None
    monitor_time: Optional[datetime] = None
    dzlxbrief: Optional[str] = None
    dztzbrief: Optional[str] = None
    hedu_eco: Optional[str] = None
    dox: Optional[Decimal] = None
    wgbh: Optional[Decimal] = None
    cond: Optional[Decimal] = None
    ph: Optional[Decimal] = None
    wyyzk: Optional[str] = None
    yd: Optional[Decimal] = None
    wq: Optional[Decimal] = None
    wtemp: Optional[Decimal] = None
    wv: Optional[Decimal] = None
    wtmd: Optional[Decimal] = None
    wzb: Optional[str] = None
    rvltpj: Optional[str] = None
    wlong: Optional[Decimal] = None
    wwidth: Optional[Decimal] = None
    wdepth: Optional[Decimal] = None
    warea: Optional[Decimal] = None
    yatzh: Optional[str] = None
    hctzh: Optional[str] = None
    zrrkzg: Optional[str] = None
    gytd: Optional[str] = None
    pazbdyx: Optional[str] = None
    abtdlylx: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class ReachBiodiversityDataCreate(BaseModel):
    """Create payload for 河段生物多样性数据表"""

    monitor_code: str
    heduan_code: Optional[str] = None
    heduan_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    fyzw_num: Optional[int] = None
    fyzw_den: Optional[Decimal] = None
    fyzw_bio: Optional[Decimal] = None
    fyzw_div: Optional[Decimal] = None
    zszl_num: Optional[int] = None
    zszl_den: Optional[Decimal] = None
    zszl_bio: Optional[Decimal] = None
    zszl_div: Optional[Decimal] = None
    fydw_num: Optional[int] = None
    fydw_den: Optional[Decimal] = None
    fydw_bio: Optional[Decimal] = None
    fydw_div: Optional[Decimal] = None
    dqdw_num: Optional[int] = None
    dqdw_den: Optional[Decimal] = None
    dqdw_bio: Optional[Decimal] = None
    dqdw_div: Optional[Decimal] = None
    fyzw_lanzao_num: Optional[int] = None
    fyzw_jinzao_num: Optional[int] = None
    fyzw_guizao_num: Optional[int] = None
    fyzw_yinzao_num: Optional[int] = None
    fyzw_jiazao_num: Optional[int] = None
    fyzw_luozao_num: Optional[int] = None
    fyzw_lvzao_num: Optional[int] = None
    fyzw_lanzao_den: Optional[Decimal] = None
    fyzw_jinzao_den: Optional[Decimal] = None
    fyzw_guizao_den: Optional[Decimal] = None
    fyzw_yinzao_den: Optional[Decimal] = None
    fyzw_jiazao_den: Optional[Decimal] = None
    fyzw_luozao_den: Optional[Decimal] = None
    fyzw_lvzao_den: Optional[Decimal] = None
    fyzw_lanzao_bio: Optional[Decimal] = None
    fyzw_jinzao_bio: Optional[Decimal] = None
    fyzw_guizao_bio: Optional[Decimal] = None
    fyzw_yinzao_bio: Optional[Decimal] = None
    fyzw_jiazao_bio: Optional[Decimal] = None
    fyzw_luozao_bio: Optional[Decimal] = None
    fyzw_lvzao_bio: Optional[Decimal] = None
    zszl_lanzao_num: Optional[int] = None
    zszl_jinzao_num: Optional[int] = None
    zszl_guizao_num: Optional[int] = None
    zszl_yinzao_num: Optional[int] = None
    zszl_jiazao_num: Optional[int] = None
    zszl_luozao_num: Optional[int] = None
    zszl_lvzao_num: Optional[int] = None
    zszl_lanzao_den: Optional[Decimal] = None
    zszl_jinzao_den: Optional[Decimal] = None
    zszl_guizao_den: Optional[Decimal] = None
    zszl_yinzao_den: Optional[Decimal] = None
    zszl_jiazao_den: Optional[Decimal] = None
    zszl_luozao_den: Optional[Decimal] = None
    zszl_lvzao_den: Optional[Decimal] = None
    zszl_lanzao_bio: Optional[Decimal] = None
    zszl_jinzao_bio: Optional[Decimal] = None
    zszl_guizao_bio: Optional[Decimal] = None
    zszl_yinzao_bio: Optional[Decimal] = None
    zszl_jiazao_bio: Optional[Decimal] = None
    zszl_luozao_bio: Optional[Decimal] = None
    zszl_lvzao_bio: Optional[Decimal] = None
    fydw_ysdw_num: Optional[int] = None
    fydw_lcl_num: Optional[int] = None
    fydw_jzl_num: Optional[int] = None
    fydw_rzl_num: Optional[int] = None
    fydw_ysdw_den: Optional[Decimal] = None
    fydw_lcl_den: Optional[Decimal] = None
    fydw_jzl_den: Optional[Decimal] = None
    fydw_rzl_den: Optional[Decimal] = None
    fydw_ysdw_bio: Optional[Decimal] = None
    fydw_lcl_bio: Optional[Decimal] = None
    fydw_jzl_bio: Optional[Decimal] = None
    fydw_rzl_bio: Optional[Decimal] = None
    dqdw_hj_num: Optional[int] = None
    dqdw_rt_num: Optional[int] = None
    dqdw_jz_num: Optional[int] = None
    dqdw_xc_num: Optional[int] = None
    dqdw_bx_num: Optional[int] = None
    dqdw_hj_den: Optional[Decimal] = None
    dqdw_rt_den: Optional[Decimal] = None
    dqdw_jz_den: Optional[Decimal] = None
    dqdw_xc_den: Optional[Decimal] = None
    dqdw_bx_den: Optional[Decimal] = None
    dqdw_hj_bio: Optional[Decimal] = None
    dqdw_rt_bio: Optional[Decimal] = None
    dqdw_jz_bio: Optional[Decimal] = None
    dqdw_xc_bio: Optional[Decimal] = None
    dqdw_bx_bio: Optional[Decimal] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class ReachBiodiversityData(BaseModel):
    """Read model for 河段生物多样性数据表"""
    model_config = ConfigDict(from_attributes=True)

    monitor_code: Optional[str] = None
    heduan_code: Optional[str] = None
    heduan_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    fyzw_num: Optional[int] = None
    fyzw_den: Optional[Decimal] = None
    fyzw_bio: Optional[Decimal] = None
    fyzw_div: Optional[Decimal] = None
    zszl_num: Optional[int] = None
    zszl_den: Optional[Decimal] = None
    zszl_bio: Optional[Decimal] = None
    zszl_div: Optional[Decimal] = None
    fydw_num: Optional[int] = None
    fydw_den: Optional[Decimal] = None
    fydw_bio: Optional[Decimal] = None
    fydw_div: Optional[Decimal] = None
    dqdw_num: Optional[int] = None
    dqdw_den: Optional[Decimal] = None
    dqdw_bio: Optional[Decimal] = None
    dqdw_div: Optional[Decimal] = None
    fyzw_lanzao_num: Optional[int] = None
    fyzw_jinzao_num: Optional[int] = None
    fyzw_guizao_num: Optional[int] = None
    fyzw_yinzao_num: Optional[int] = None
    fyzw_jiazao_num: Optional[int] = None
    fyzw_luozao_num: Optional[int] = None
    fyzw_lvzao_num: Optional[int] = None
    fyzw_lanzao_den: Optional[Decimal] = None
    fyzw_jinzao_den: Optional[Decimal] = None
    fyzw_guizao_den: Optional[Decimal] = None
    fyzw_yinzao_den: Optional[Decimal] = None
    fyzw_jiazao_den: Optional[Decimal] = None
    fyzw_luozao_den: Optional[Decimal] = None
    fyzw_lvzao_den: Optional[Decimal] = None
    fyzw_lanzao_bio: Optional[Decimal] = None
    fyzw_jinzao_bio: Optional[Decimal] = None
    fyzw_guizao_bio: Optional[Decimal] = None
    fyzw_yinzao_bio: Optional[Decimal] = None
    fyzw_jiazao_bio: Optional[Decimal] = None
    fyzw_luozao_bio: Optional[Decimal] = None
    fyzw_lvzao_bio: Optional[Decimal] = None
    zszl_lanzao_num: Optional[int] = None
    zszl_jinzao_num: Optional[int] = None
    zszl_guizao_num: Optional[int] = None
    zszl_yinzao_num: Optional[int] = None
    zszl_jiazao_num: Optional[int] = None
    zszl_luozao_num: Optional[int] = None
    zszl_lvzao_num: Optional[int] = None
    zszl_lanzao_den: Optional[Decimal] = None
    zszl_jinzao_den: Optional[Decimal] = None
    zszl_guizao_den: Optional[Decimal] = None
    zszl_yinzao_den: Optional[Decimal] = None
    zszl_jiazao_den: Optional[Decimal] = None
    zszl_luozao_den: Optional[Decimal] = None
    zszl_lvzao_den: Optional[Decimal] = None
    zszl_lanzao_bio: Optional[Decimal] = None
    zszl_jinzao_bio: Optional[Decimal] = None
    zszl_guizao_bio: Optional[Decimal] = None
    zszl_yinzao_bio: Optional[Decimal] = None
    zszl_jiazao_bio: Optional[Decimal] = None
    zszl_luozao_bio: Optional[Decimal] = None
    zszl_lvzao_bio: Optional[Decimal] = None
    fydw_ysdw_num: Optional[int] = None
    fydw_lcl_num: Optional[int] = None
    fydw_jzl_num: Optional[int] = None
    fydw_rzl_num: Optional[int] = None
    fydw_ysdw_den: Optional[Decimal] = None
    fydw_lcl_den: Optional[Decimal] = None
    fydw_jzl_den: Optional[Decimal] = None
    fydw_rzl_den: Optional[Decimal] = None
    fydw_ysdw_bio: Optional[Decimal] = None
    fydw_lcl_bio: Optional[Decimal] = None
    fydw_jzl_bio: Optional[Decimal] = None
    fydw_rzl_bio: Optional[Decimal] = None
    dqdw_hj_num: Optional[int] = None
    dqdw_rt_num: Optional[int] = None
    dqdw_jz_num: Optional[int] = None
    dqdw_xc_num: Optional[int] = None
    dqdw_bx_num: Optional[int] = None
    dqdw_hj_den: Optional[Decimal] = None
    dqdw_rt_den: Optional[Decimal] = None
    dqdw_jz_den: Optional[Decimal] = None
    dqdw_xc_den: Optional[Decimal] = None
    dqdw_bx_den: Optional[Decimal] = None
    dqdw_hj_bio: Optional[Decimal] = None
    dqdw_rt_bio: Optional[Decimal] = None
    dqdw_jz_bio: Optional[Decimal] = None
    dqdw_xc_bio: Optional[Decimal] = None
    dqdw_bx_bio: Optional[Decimal] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class ReachBioSurveyDataCreate(BaseModel):
    """Create payload for 河段生物调查数据表"""

    monitor_code: str
    heduan_code: Optional[str] = None
    heduan_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    mglatinm: Optional[str] = None
    mgnm: Optional[str] = None
    latinm: Optional[str] = None
    chnm: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class ReachBioSurveyData(BaseModel):
    """Read model for 河段生物调查数据表"""
    model_config = ConfigDict(from_attributes=True)

    monitor_code: Optional[str] = None
    heduan_code: Optional[str] = None
    heduan_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    mglatinm: Optional[str] = None
    mgnm: Optional[str] = None
    latinm: Optional[str] = None
    chnm: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class FishSpeciesCreate(BaseModel):
    """Create payload for 鱼类物种表"""

    fish_code: str
    fish_name: Optional[str] = None
    fish_latin: Optional[str] = None
    proty: Optional[str] = None
    kindom: Optional[str] = None
    klass: Optional[str] = None
    bio_order: Optional[str] = None
    family: Optional[str] = None
    genus: Optional[str] = None
    species: Optional[str] = None
    appchara: Optional[str] = None
    speciestpye: Optional[str] = None
    protection_level: Optional[str] = None
    endangered_status: Optional[str] = None
    specificity: Optional[str] = None
    area: Optional[str] = None
    internal: Optional[str] = None
    food: Optional[str] = None
    habits: Optional[str] = None
    reproduction: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class FishSpecies(BaseModel):
    """Read model for 鱼类物种表"""
    model_config = ConfigDict(from_attributes=True)

    fish_code: Optional[str] = None
    fish_name: Optional[str] = None
    fish_latin: Optional[str] = None
    proty: Optional[str] = None
    kindom: Optional[str] = None
    klass: Optional[str] = None
    bio_order: Optional[str] = None
    family: Optional[str] = None
    genus: Optional[str] = None
    species: Optional[str] = None
    appchara: Optional[str] = None
    speciestpye: Optional[str] = None
    protection_level: Optional[str] = None
    endangered_status: Optional[str] = None
    specificity: Optional[str] = None
    area: Optional[str] = None
    internal: Optional[str] = None
    food: Optional[str] = None
    habits: Optional[str] = None
    reproduction: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class FishCatchDataCreate(BaseModel):
    """Create payload for 渔获物数据表"""

    monitor_code: str
    heduan_code: Optional[str] = None
    heduan_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    type: Optional[str] = None
    fish_name: Optional[str] = None
    fish_code: Optional[str] = None
    fish_num: Optional[int] = None
    num_ratio: Optional[int] = None
    weight_ratio: Optional[Decimal] = None
    length_range: Optional[str] = None
    weight_range: Optional[str] = None
    xcsqy_ratio: Optional[Decimal] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class FishCatchData(BaseModel):
    """Read model for 渔获物数据表"""
    model_config = ConfigDict(from_attributes=True)

    monitor_code: Optional[str] = None
    heduan_code: Optional[str] = None
    heduan_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    type: Optional[str] = None
    fish_name: Optional[str] = None
    fish_code: Optional[str] = None
    fish_num: Optional[int] = None
    num_ratio: Optional[int] = None
    weight_ratio: Optional[Decimal] = None
    length_range: Optional[str] = None
    weight_range: Optional[str] = None
    xcsqy_ratio: Optional[Decimal] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class FishDiversityDataCreate(BaseModel):
    """Create payload for 鱼类多样性信息表"""

    monitor_code: str
    fish_name: Optional[str] = None
    fish_code: Optional[str] = None
    div_index: Optional[Decimal] = None
    div_description: Optional[str] = None
    dif_description: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class FishDiversityData(BaseModel):
    """Read model for 鱼类多样性信息表"""
    model_config = ConfigDict(from_attributes=True)

    monitor_code: Optional[str] = None
    fish_name: Optional[str] = None
    fish_code: Optional[str] = None
    div_index: Optional[Decimal] = None
    div_description: Optional[str] = None
    dif_description: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class FishGroundsCreate(BaseModel):
    """Create payload for 鱼类三场"""

    field_code: str
    field_name: Optional[str] = None
    type: Optional[str] = None
    location: Optional[str] = None
    length: Optional[Decimal] = None
    width: Optional[Decimal] = None
    area: Optional[Decimal] = None
    depth: Optional[Decimal] = None
    wt: Optional[Decimal] = None
    species: Optional[str] = None
    substrate: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class FishGrounds(BaseModel):
    """Read model for 鱼类三场"""
    model_config = ConfigDict(from_attributes=True)

    field_code: Optional[str] = None
    field_name: Optional[str] = None
    type: Optional[str] = None
    location: Optional[str] = None
    length: Optional[Decimal] = None
    width: Optional[Decimal] = None
    area: Optional[Decimal] = None
    depth: Optional[Decimal] = None
    wt: Optional[Decimal] = None
    species: Optional[str] = None
    substrate: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class AquaReachInfoCreate(BaseModel):
    """Create payload for 水生生态监测河段信息表"""

    heduan_code: str
    heduan_name: Optional[str] = None
    type: Optional[str] = None
    river: Optional[str] = None
    start_longitude: Optional[Decimal] = None
    start_latitude: Optional[Decimal] = None
    start_altitude: Optional[Decimal] = None
    end_longitude: Optional[Decimal] = None
    end_latitude: Optional[Decimal] = None
    end_altitude: Optional[Decimal] = None
    length: Optional[str] = None
    wt: Optional[Decimal] = None
    dox: Optional[Decimal] = None
    ph: Optional[Decimal] = None
    cond: Optional[Decimal] = None
    flow_velocity: Optional[Decimal] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class AquaReachInfo(BaseModel):
    """Read model for 水生生态监测河段信息表"""
    model_config = ConfigDict(from_attributes=True)

    heduan_code: Optional[str] = None
    heduan_name: Optional[str] = None
    type: Optional[str] = None
    river: Optional[str] = None
    start_longitude: Optional[Decimal] = None
    start_latitude: Optional[Decimal] = None
    start_altitude: Optional[Decimal] = None
    end_longitude: Optional[Decimal] = None
    end_latitude: Optional[Decimal] = None
    end_altitude: Optional[Decimal] = None
    length: Optional[str] = None
    wt: Optional[Decimal] = None
    dox: Optional[Decimal] = None
    ph: Optional[Decimal] = None
    cond: Optional[Decimal] = None
    flow_velocity: Optional[Decimal] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class SurveyPointInfoCreate(BaseModel):
    """Create payload for 调查点位信息表"""

    sp_code: str
    sp_name: Optional[str] = None
    type: Optional[str] = None
    river: Optional[str] = None
    wt: Optional[Decimal] = None
    dox: Optional[Decimal] = None
    ph: Optional[Decimal] = None
    cond: Optional[Decimal] = None
    flow_velocity: Optional[Decimal] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class SurveyPointInfo(BaseModel):
    """Read model for 调查点位信息表"""
    model_config = ConfigDict(from_attributes=True)

    sp_code: Optional[str] = None
    sp_name: Optional[str] = None
    type: Optional[str] = None
    river: Optional[str] = None
    wt: Optional[Decimal] = None
    dox: Optional[Decimal] = None
    ph: Optional[Decimal] = None
    cond: Optional[Decimal] = None
    flow_velocity: Optional[Decimal] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None
