# -*- coding: utf-8 -*-
"""
Pydantic v2 schemas - 01水环境. Auto-generated by tools/build_schema.py.
"""
from datetime import datetime
from decimal import Decimal
from typing import Optional
from pydantic import BaseModel, ConfigDict

class HydroStationCreate(BaseModel):
    """Create payload for 水文情势测站信息表"""

    station_code: str
    station_name: Optional[str] = None
    longitude: Optional[Decimal] = None
    latitude: Optional[Decimal] = None
    altitude: Optional[Decimal] = None
    location: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class HydroStation(BaseModel):
    """Read model for 水文情势测站信息表"""
    model_config = ConfigDict(from_attributes=True)

    station_code: Optional[str] = None
    station_name: Optional[str] = None
    longitude: Optional[Decimal] = None
    latitude: Optional[Decimal] = None
    altitude: Optional[Decimal] = None
    location: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class HydroDataCreate(BaseModel):
    """Create payload for 水文情势监测数据表"""

    monitor_code: str
    station_code: Optional[str] = None
    station_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    water_level: Optional[Decimal] = None
    traffic: Optional[Decimal] = None
    rainfall: Optional[Decimal] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class HydroData(BaseModel):
    """Read model for 水文情势监测数据表"""
    model_config = ConfigDict(from_attributes=True)

    monitor_code: Optional[str] = None
    station_code: Optional[str] = None
    station_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    water_level: Optional[Decimal] = None
    traffic: Optional[Decimal] = None
    rainfall: Optional[Decimal] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class AutoSurfaceWaterStationCreate(BaseModel):
    """Create payload for 自动地表水水质测站信息表"""

    station_code: str
    station_name: Optional[str] = None
    longitude: Optional[Decimal] = None
    latitude: Optional[Decimal] = None
    altitude: Optional[Decimal] = None
    location: Optional[str] = None
    monitor_river: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class AutoSurfaceWaterStation(BaseModel):
    """Read model for 自动地表水水质测站信息表"""
    model_config = ConfigDict(from_attributes=True)

    station_code: Optional[str] = None
    station_name: Optional[str] = None
    longitude: Optional[Decimal] = None
    latitude: Optional[Decimal] = None
    altitude: Optional[Decimal] = None
    location: Optional[str] = None
    monitor_river: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class AutoSurfaceWaterDataCreate(BaseModel):
    """Create payload for 自动地表水水质监测数据表"""

    monitor_code: str
    station_code: Optional[str] = None
    station_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    wt: Optional[Decimal] = None
    turb: Optional[Decimal] = None
    cond: Optional[Decimal] = None
    tn: Optional[Decimal] = None
    ph: Optional[Decimal] = None
    dox: Optional[Decimal] = None
    codmn: Optional[Decimal] = None
    nh3n: Optional[Decimal] = None
    tp: Optional[Decimal] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class AutoSurfaceWaterData(BaseModel):
    """Read model for 自动地表水水质监测数据表"""
    model_config = ConfigDict(from_attributes=True)

    monitor_code: Optional[str] = None
    station_code: Optional[str] = None
    station_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    wt: Optional[Decimal] = None
    turb: Optional[Decimal] = None
    cond: Optional[Decimal] = None
    tn: Optional[Decimal] = None
    ph: Optional[Decimal] = None
    dox: Optional[Decimal] = None
    codmn: Optional[Decimal] = None
    nh3n: Optional[Decimal] = None
    tp: Optional[Decimal] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class ManualSurfaceWaterStationCreate(BaseModel):
    """Create payload for 人工地表水水质测站信息表"""

    station_code: str
    station_name: Optional[str] = None
    longitude: Optional[Decimal] = None
    latitude: Optional[Decimal] = None
    altitude: Optional[Decimal] = None
    location: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class ManualSurfaceWaterStation(BaseModel):
    """Read model for 人工地表水水质测站信息表"""
    model_config = ConfigDict(from_attributes=True)

    station_code: Optional[str] = None
    station_name: Optional[str] = None
    longitude: Optional[Decimal] = None
    latitude: Optional[Decimal] = None
    altitude: Optional[Decimal] = None
    location: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class ManualSurfaceWaterDataCreate(BaseModel):
    """Create payload for 人工地表水水质监测数据表"""

    monitor_code: str
    station_code: Optional[str] = None
    station_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    wt: Optional[Decimal] = None
    ph: Optional[Decimal] = None
    dox: Optional[Decimal] = None
    codmn: Optional[Decimal] = None
    codcr: Optional[Decimal] = None
    bod5: Optional[Decimal] = None
    nh3n: Optional[Decimal] = None
    oil: Optional[Decimal] = None
    vlph: Optional[Decimal] = None
    hg: Optional[Decimal] = None
    pb: Optional[Decimal] = None
    tn: Optional[Decimal] = None
    tp: Optional[Decimal] = None
    cu: Optional[Decimal] = None
    zn: Optional[Decimal] = None
    f: Optional[Decimal] = None
    se: Optional[Decimal] = None
    ars: Optional[Decimal] = None
    cd: Optional[Decimal] = None
    cn: Optional[Decimal] = None
    las: Optional[Decimal] = None
    s2: Optional[Decimal] = None
    fcg: Optional[Decimal] = None
    ss: Optional[Decimal] = None
    ll: Optional[Decimal] = None
    cond: Optional[Decimal] = None
    sulfate: Optional[Decimal] = None
    chloride: Optional[Decimal] = None
    nitrate: Optional[Decimal] = None
    fe: Optional[Decimal] = None
    mn: Optional[Decimal] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class ManualSurfaceWaterData(BaseModel):
    """Read model for 人工地表水水质监测数据表"""
    model_config = ConfigDict(from_attributes=True)

    monitor_code: Optional[str] = None
    station_code: Optional[str] = None
    station_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    wt: Optional[Decimal] = None
    ph: Optional[Decimal] = None
    dox: Optional[Decimal] = None
    codmn: Optional[Decimal] = None
    codcr: Optional[Decimal] = None
    bod5: Optional[Decimal] = None
    nh3n: Optional[Decimal] = None
    oil: Optional[Decimal] = None
    vlph: Optional[Decimal] = None
    hg: Optional[Decimal] = None
    pb: Optional[Decimal] = None
    tn: Optional[Decimal] = None
    tp: Optional[Decimal] = None
    cu: Optional[Decimal] = None
    zn: Optional[Decimal] = None
    f: Optional[Decimal] = None
    se: Optional[Decimal] = None
    ars: Optional[Decimal] = None
    cd: Optional[Decimal] = None
    cn: Optional[Decimal] = None
    las: Optional[Decimal] = None
    s2: Optional[Decimal] = None
    fcg: Optional[Decimal] = None
    ss: Optional[Decimal] = None
    ll: Optional[Decimal] = None
    cond: Optional[Decimal] = None
    sulfate: Optional[Decimal] = None
    chloride: Optional[Decimal] = None
    nitrate: Optional[Decimal] = None
    fe: Optional[Decimal] = None
    mn: Optional[Decimal] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class SedimentStationCreate(BaseModel):
    """Create payload for 沉积物测站信息表"""

    station_code: str
    station_name: Optional[str] = None
    longitude: Optional[Decimal] = None
    latitude: Optional[Decimal] = None
    altitude: Optional[Decimal] = None
    location: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class SedimentStation(BaseModel):
    """Read model for 沉积物测站信息表"""
    model_config = ConfigDict(from_attributes=True)

    station_code: Optional[str] = None
    station_name: Optional[str] = None
    longitude: Optional[Decimal] = None
    latitude: Optional[Decimal] = None
    altitude: Optional[Decimal] = None
    location: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class SedimentDataCreate(BaseModel):
    """Create payload for 沉积物监测数据表"""

    monitor_code: str
    station_code: Optional[str] = None
    station_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    alpha_hch: Optional[Decimal] = None
    beta_hch: Optional[Decimal] = None
    gamma_hch: Optional[Decimal] = None
    delta_hch: Optional[Decimal] = None
    dde_4_4: Optional[Decimal] = None
    ddd_4_4: Optional[Decimal] = None
    ddt_2_4: Optional[Decimal] = None
    ddt_4_4: Optional[Decimal] = None
    c10h8: Optional[Decimal] = None
    c12h8: Optional[Decimal] = None
    c12h10: Optional[Decimal] = None
    c13h10: Optional[Decimal] = None
    c14h10_fei: Optional[Decimal] = None
    c14h10_en: Optional[Decimal] = None
    c16h10_yingen: Optional[Decimal] = None
    c16h10_p: Optional[Decimal] = None
    c18d12: Optional[Decimal] = None
    c18h12: Optional[Decimal] = None
    c20h12_b: Optional[Decimal] = None
    c20h12_k: Optional[Decimal] = None
    c20h12_a: Optional[Decimal] = None
    c22h12_1_2_3_cd: Optional[Decimal] = None
    c22h14: Optional[Decimal] = None
    c22h12_g_h_i: Optional[Decimal] = None
    c4h7cl2o4p: Optional[Decimal] = None
    c7h13o6p: Optional[Decimal] = None
    c8h13n2o3ps: Optional[Decimal] = None
    c8h19o3ps2_o: Optional[Decimal] = None
    c8h19o2ps2: Optional[Decimal] = None
    c8h20o5p2s2: Optional[Decimal] = None
    c7h17o2ps3: Optional[Decimal] = None
    c8h19o3ps2_s: Optional[Decimal] = None
    c5h12no3ps2: Optional[Decimal] = None
    c12h21n2o3ps: Optional[Decimal] = None
    c8h19o2ps3: Optional[Decimal] = None
    c6h12no4ps2: Optional[Decimal] = None
    c8h10no5ps: Optional[Decimal] = None
    pml: Optional[Decimal] = None
    c10h19o6ps2: Optional[Decimal] = None
    c9h11cl3no3ps: Optional[Decimal] = None
    c7h17o4ps3: Optional[Decimal] = None
    c10h15o3ps2: Optional[Decimal] = None
    c10h14no5ps: Optional[Decimal] = None
    c14h16cln3o2: Optional[Decimal] = None
    c12h19clno3p: Optional[Decimal] = None
    c10h12cl3o2ps: Optional[Decimal] = None
    c12h4cl2f6n4os: Optional[Decimal] = None
    c10h20no5ps2: Optional[Decimal] = None
    c8h16no3ps2: Optional[Decimal] = None
    c10h9cl4o4p: Optional[Decimal] = None
    c11h15cl2o2ps2: Optional[Decimal] = None
    c12h27ps3: Optional[Decimal] = None
    c11h17o4ps2: Optional[Decimal] = None
    c10h15o6ps: Optional[Decimal] = None
    c11h16clo2ps3: Optional[Decimal] = None
    c9h6cl6o4s: Optional[Decimal] = None
    c19h30o5: Optional[Decimal] = None
    c14h14no4ps: Optional[Decimal] = None
    c17h16br2o3: Optional[Decimal] = None
    c13h10brcl2o2ps: Optional[Decimal] = None
    c14h18cln2o3ps: Optional[Decimal] = None
    c14h16clo5ps: Optional[Decimal] = None
    ch3cl: Optional[Decimal] = None
    c2h3cl: Optional[Decimal] = None
    c2h2cl2: Optional[Decimal] = None
    ch2cl2: Optional[Decimal] = None
    f_c2h2cl2: Optional[Decimal] = None
    c2h4cl2_1_1: Optional[Decimal] = None
    s_c2h2cl2: Optional[Decimal] = None
    chcl3: Optional[Decimal] = None
    c2h3cl3_1_1_1: Optional[Decimal] = None
    ccl4: Optional[Decimal] = None
    c6h6: Optional[Decimal] = None
    c2h4cl2_1_2: Optional[Decimal] = None
    c2hcl3: Optional[Decimal] = None
    c3h6cl2: Optional[Decimal] = None
    c7h8: Optional[Decimal] = None
    c2h3cl3_1_1_2: Optional[Decimal] = None
    c2cl4: Optional[Decimal] = None
    c6h5cl: Optional[Decimal] = None
    c2h2cl4_1_1_1_2: Optional[Decimal] = None
    c8h10: Optional[Decimal] = None
    j_d_c8h10: Optional[Decimal] = None
    l_c8h10: Optional[Decimal] = None
    c8h8: Optional[Decimal] = None
    c2h2cl4_1_1_2_2: Optional[Decimal] = None
    c3h5cl3: Optional[Decimal] = None
    c6h4cl2_1_4: Optional[Decimal] = None
    c6h4cl2_1_2: Optional[Decimal] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class SedimentData(BaseModel):
    """Read model for 沉积物监测数据表"""
    model_config = ConfigDict(from_attributes=True)

    monitor_code: Optional[str] = None
    station_code: Optional[str] = None
    station_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    alpha_hch: Optional[Decimal] = None
    beta_hch: Optional[Decimal] = None
    gamma_hch: Optional[Decimal] = None
    delta_hch: Optional[Decimal] = None
    dde_4_4: Optional[Decimal] = None
    ddd_4_4: Optional[Decimal] = None
    ddt_2_4: Optional[Decimal] = None
    ddt_4_4: Optional[Decimal] = None
    c10h8: Optional[Decimal] = None
    c12h8: Optional[Decimal] = None
    c12h10: Optional[Decimal] = None
    c13h10: Optional[Decimal] = None
    c14h10_fei: Optional[Decimal] = None
    c14h10_en: Optional[Decimal] = None
    c16h10_yingen: Optional[Decimal] = None
    c16h10_p: Optional[Decimal] = None
    c18d12: Optional[Decimal] = None
    c18h12: Optional[Decimal] = None
    c20h12_b: Optional[Decimal] = None
    c20h12_k: Optional[Decimal] = None
    c20h12_a: Optional[Decimal] = None
    c22h12_1_2_3_cd: Optional[Decimal] = None
    c22h14: Optional[Decimal] = None
    c22h12_g_h_i: Optional[Decimal] = None
    c4h7cl2o4p: Optional[Decimal] = None
    c7h13o6p: Optional[Decimal] = None
    c8h13n2o3ps: Optional[Decimal] = None
    c8h19o3ps2_o: Optional[Decimal] = None
    c8h19o2ps2: Optional[Decimal] = None
    c8h20o5p2s2: Optional[Decimal] = None
    c7h17o2ps3: Optional[Decimal] = None
    c8h19o3ps2_s: Optional[Decimal] = None
    c5h12no3ps2: Optional[Decimal] = None
    c12h21n2o3ps: Optional[Decimal] = None
    c8h19o2ps3: Optional[Decimal] = None
    c6h12no4ps2: Optional[Decimal] = None
    c8h10no5ps: Optional[Decimal] = None
    pml: Optional[Decimal] = None
    c10h19o6ps2: Optional[Decimal] = None
    c9h11cl3no3ps: Optional[Decimal] = None
    c7h17o4ps3: Optional[Decimal] = None
    c10h15o3ps2: Optional[Decimal] = None
    c10h14no5ps: Optional[Decimal] = None
    c14h16cln3o2: Optional[Decimal] = None
    c12h19clno3p: Optional[Decimal] = None
    c10h12cl3o2ps: Optional[Decimal] = None
    c12h4cl2f6n4os: Optional[Decimal] = None
    c10h20no5ps2: Optional[Decimal] = None
    c8h16no3ps2: Optional[Decimal] = None
    c10h9cl4o4p: Optional[Decimal] = None
    c11h15cl2o2ps2: Optional[Decimal] = None
    c12h27ps3: Optional[Decimal] = None
    c11h17o4ps2: Optional[Decimal] = None
    c10h15o6ps: Optional[Decimal] = None
    c11h16clo2ps3: Optional[Decimal] = None
    c9h6cl6o4s: Optional[Decimal] = None
    c19h30o5: Optional[Decimal] = None
    c14h14no4ps: Optional[Decimal] = None
    c17h16br2o3: Optional[Decimal] = None
    c13h10brcl2o2ps: Optional[Decimal] = None
    c14h18cln2o3ps: Optional[Decimal] = None
    c14h16clo5ps: Optional[Decimal] = None
    ch3cl: Optional[Decimal] = None
    c2h3cl: Optional[Decimal] = None
    c2h2cl2: Optional[Decimal] = None
    ch2cl2: Optional[Decimal] = None
    f_c2h2cl2: Optional[Decimal] = None
    c2h4cl2_1_1: Optional[Decimal] = None
    s_c2h2cl2: Optional[Decimal] = None
    chcl3: Optional[Decimal] = None
    c2h3cl3_1_1_1: Optional[Decimal] = None
    ccl4: Optional[Decimal] = None
    c6h6: Optional[Decimal] = None
    c2h4cl2_1_2: Optional[Decimal] = None
    c2hcl3: Optional[Decimal] = None
    c3h6cl2: Optional[Decimal] = None
    c7h8: Optional[Decimal] = None
    c2h3cl3_1_1_2: Optional[Decimal] = None
    c2cl4: Optional[Decimal] = None
    c6h5cl: Optional[Decimal] = None
    c2h2cl4_1_1_1_2: Optional[Decimal] = None
    c8h10: Optional[Decimal] = None
    j_d_c8h10: Optional[Decimal] = None
    l_c8h10: Optional[Decimal] = None
    c8h8: Optional[Decimal] = None
    c2h2cl4_1_1_2_2: Optional[Decimal] = None
    c3h5cl3: Optional[Decimal] = None
    c6h4cl2_1_4: Optional[Decimal] = None
    c6h4cl2_1_2: Optional[Decimal] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class AutoWaterTempStationCreate(BaseModel):
    """Create payload for 自动水温测站信息表"""

    station_code: str
    station_name: Optional[str] = None
    longitude: Optional[Decimal] = None
    latitude: Optional[Decimal] = None
    altitude: Optional[Decimal] = None
    location: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class AutoWaterTempStation(BaseModel):
    """Read model for 自动水温测站信息表"""
    model_config = ConfigDict(from_attributes=True)

    station_code: Optional[str] = None
    station_name: Optional[str] = None
    longitude: Optional[Decimal] = None
    latitude: Optional[Decimal] = None
    altitude: Optional[Decimal] = None
    location: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class AutoWaterTempDataCreate(BaseModel):
    """Create payload for 自动水温监测数据表"""

    monitor_code: str
    station_code: Optional[str] = None
    station_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    cond: Optional[Decimal] = None
    wt: Optional[Decimal] = None

class AutoWaterTempData(BaseModel):
    """Read model for 自动水温监测数据表"""
    model_config = ConfigDict(from_attributes=True)

    monitor_code: Optional[str] = None
    station_code: Optional[str] = None
    station_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    cond: Optional[Decimal] = None
    wt: Optional[Decimal] = None

class AutoGroundwaterLevelStationCreate(BaseModel):
    """Create payload for 自动地下水水位测站信息表"""

    station_code: str
    station_name: Optional[str] = None
    longitude: Optional[Decimal] = None
    latitude: Optional[Decimal] = None
    altitude: Optional[Decimal] = None
    location: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class AutoGroundwaterLevelStation(BaseModel):
    """Read model for 自动地下水水位测站信息表"""
    model_config = ConfigDict(from_attributes=True)

    station_code: Optional[str] = None
    station_name: Optional[str] = None
    longitude: Optional[Decimal] = None
    latitude: Optional[Decimal] = None
    altitude: Optional[Decimal] = None
    location: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class AutoGroundwaterLevelDataCreate(BaseModel):
    """Create payload for 自动地下水水位监测数据表"""

    monitor_code: str
    station_code: Optional[str] = None
    station_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    water_level: Optional[Decimal] = None
    bd: Optional[Decimal] = None
    elevation: Optional[Decimal] = None
    depth: Optional[Decimal] = None
    cond: Optional[Decimal] = None
    wt: Optional[Decimal] = None

class AutoGroundwaterLevelData(BaseModel):
    """Read model for 自动地下水水位监测数据表"""
    model_config = ConfigDict(from_attributes=True)

    monitor_code: Optional[str] = None
    station_code: Optional[str] = None
    station_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    water_level: Optional[Decimal] = None
    bd: Optional[Decimal] = None
    elevation: Optional[Decimal] = None
    depth: Optional[Decimal] = None
    cond: Optional[Decimal] = None
    wt: Optional[Decimal] = None

class ManualGroundwaterQualityStationCreate(BaseModel):
    """Create payload for 人工地下水水质测站信息表"""

    station_code: str
    station_name: Optional[str] = None
    longitude: Optional[Decimal] = None
    latitude: Optional[Decimal] = None
    altitude: Optional[Decimal] = None
    location: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class ManualGroundwaterQualityStation(BaseModel):
    """Read model for 人工地下水水质测站信息表"""
    model_config = ConfigDict(from_attributes=True)

    station_code: Optional[str] = None
    station_name: Optional[str] = None
    longitude: Optional[Decimal] = None
    latitude: Optional[Decimal] = None
    altitude: Optional[Decimal] = None
    location: Optional[str] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class ManualGroundwaterQualityDataCreate(BaseModel):
    """Create payload for 人工地下水水质监测数据表"""

    monitor_code: str
    station_code: Optional[str] = None
    station_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    spdeepth: Optional[Decimal] = None
    ph: Optional[Decimal] = None
    nh3n: Optional[Decimal] = None
    nitrate: Optional[Decimal] = None
    nitrite: Optional[Decimal] = None
    vlph: Optional[Decimal] = None
    cn: Optional[Decimal] = None
    ars: Optional[Decimal] = None
    hg: Optional[Decimal] = None
    cr6: Optional[Decimal] = None
    thrd: Optional[Decimal] = None
    pb: Optional[Decimal] = None
    f: Optional[Decimal] = None
    cd: Optional[Decimal] = None
    fe: Optional[Decimal] = None
    mn: Optional[Decimal] = None
    tds: Optional[Decimal] = None
    codmn: Optional[Decimal] = None
    sulfate: Optional[Decimal] = None
    cl: Optional[Decimal] = None
    fcg: Optional[Decimal] = None
    bctc: Optional[Decimal] = None
    wt: Optional[Decimal] = None
    cond: Optional[Decimal] = None
    turb: Optional[Decimal] = None
    chcl3: Optional[Decimal] = None
    ccl4: Optional[Decimal] = None
    c6h6: Optional[Decimal] = None
    c7h8: Optional[Decimal] = None
    se: Optional[Decimal] = None
    cu: Optional[Decimal] = None
    zn: Optional[Decimal] = None
    al: Optional[Decimal] = None
    na: Optional[Decimal] = None
    s2: Optional[Decimal] = None
    las: Optional[Decimal] = None
    sd: Optional[Decimal] = None
    i: Optional[Decimal] = None
    alpha: Optional[Decimal] = None
    beta: Optional[Decimal] = None
    mg: Optional[Decimal] = None
    k: Optional[Decimal] = None
    ca: Optional[Decimal] = None
    mo: Optional[Decimal] = None
    co: Optional[Decimal] = None
    be: Optional[Decimal] = None
    sb: Optional[Decimal] = None
    ba: Optional[Decimal] = None
    v: Optional[Decimal] = None
    tl: Optional[Decimal] = None
    ti: Optional[Decimal] = None
    cr: Optional[Decimal] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None

class ManualGroundwaterQualityData(BaseModel):
    """Read model for 人工地下水水质监测数据表"""
    model_config = ConfigDict(from_attributes=True)

    monitor_code: Optional[str] = None
    station_code: Optional[str] = None
    station_name: Optional[str] = None
    monitor_time: Optional[datetime] = None
    spdeepth: Optional[Decimal] = None
    ph: Optional[Decimal] = None
    nh3n: Optional[Decimal] = None
    nitrate: Optional[Decimal] = None
    nitrite: Optional[Decimal] = None
    vlph: Optional[Decimal] = None
    cn: Optional[Decimal] = None
    ars: Optional[Decimal] = None
    hg: Optional[Decimal] = None
    cr6: Optional[Decimal] = None
    thrd: Optional[Decimal] = None
    pb: Optional[Decimal] = None
    f: Optional[Decimal] = None
    cd: Optional[Decimal] = None
    fe: Optional[Decimal] = None
    mn: Optional[Decimal] = None
    tds: Optional[Decimal] = None
    codmn: Optional[Decimal] = None
    sulfate: Optional[Decimal] = None
    cl: Optional[Decimal] = None
    fcg: Optional[Decimal] = None
    bctc: Optional[Decimal] = None
    wt: Optional[Decimal] = None
    cond: Optional[Decimal] = None
    turb: Optional[Decimal] = None
    chcl3: Optional[Decimal] = None
    ccl4: Optional[Decimal] = None
    c6h6: Optional[Decimal] = None
    c7h8: Optional[Decimal] = None
    se: Optional[Decimal] = None
    cu: Optional[Decimal] = None
    zn: Optional[Decimal] = None
    al: Optional[Decimal] = None
    na: Optional[Decimal] = None
    s2: Optional[Decimal] = None
    las: Optional[Decimal] = None
    sd: Optional[Decimal] = None
    i: Optional[Decimal] = None
    alpha: Optional[Decimal] = None
    beta: Optional[Decimal] = None
    mg: Optional[Decimal] = None
    k: Optional[Decimal] = None
    ca: Optional[Decimal] = None
    mo: Optional[Decimal] = None
    co: Optional[Decimal] = None
    be: Optional[Decimal] = None
    sb: Optional[Decimal] = None
    ba: Optional[Decimal] = None
    v: Optional[Decimal] = None
    tl: Optional[Decimal] = None
    ti: Optional[Decimal] = None
    cr: Optional[Decimal] = None
    tag_org_code: Optional[str] = None
    tag_supplier_code: Optional[str] = None
    tag_creator_code: Optional[str] = None
    tag_reviser_code: Optional[str] = None
    tag_equip_code: Optional[str] = None
    tag_station_code: Optional[str] = None
    tag_time_create: Optional[datetime] = None
    tag_time_update: Optional[datetime] = None
    tag_lon: Optional[Decimal] = None
    tag_lat: Optional[Decimal] = None
    tag_alt: Optional[Decimal] = None
    tag_srs: Optional[str] = None
