# -*- coding: utf-8 -*-
"""
SQLAlchemy ORM models - 01水环境. Auto-generated by tools/build_schema.py.
Field types/comments derive from the source xlsx templates.
"""
from sqlalchemy import Column, DECIMAL, DateTime, ForeignKey, Integer, String, Text
from app.models.base import Base

class HydroStation(Base):
    """水文情势测站信息表 (hydro_station)"""
    __tablename__ = "hydro_station"
    __table_args__ = {"comment": "水文情势测站信息表"}

    station_code = Column(String(64), primary_key=True, nullable=False, comment="测站编码（主键）")
    station_name = Column(String(255), nullable=True, comment="测站名称")
    longitude = Column(DECIMAL(10,6), nullable=True, comment="经度（°）")
    latitude = Column(DECIMAL(10,6), nullable=True, comment="纬度（°）")
    altitude = Column(DECIMAL(10,3), nullable=True, comment="海拔")
    location = Column(String(255), nullable=True, comment="位置")
    tag_org_code = Column(String(64), nullable=True, comment="内部创建人所在组织编码")
    tag_supplier_code = Column(String(64), nullable=True, comment="外部创建人所属供应商编码")
    tag_creator_code = Column(String(64), nullable=True, comment="数据记录创建人编码")
    tag_reviser_code = Column(String(64), nullable=True, comment="数据记录最后修改人编码")
    tag_equip_code = Column(String(64), nullable=True, comment="数据采集设备编码")
    tag_station_code = Column(String(64), nullable=True, comment="数据采集监测站编码")
    tag_time_create = Column(DateTime, nullable=True, comment="数据记录创建或采集的时间")
    tag_time_update = Column(DateTime, nullable=True, comment="数据记录最后修改时间")
    tag_lon = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在经度(°)")
    tag_lat = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在纬度(°)")
    tag_alt = Column(DECIMAL(10,3), nullable=True, comment="数据采集设备所在海拔")
    tag_srs = Column(String(128), nullable=True, comment="CGCS2000,WGS84, 北京54，西安80")


class HydroData(Base):
    """水文情势监测数据表 (hydro_data)"""
    __tablename__ = "hydro_data"
    __table_args__ = {"comment": "水文情势监测数据表"}

    monitor_code = Column(String(64), primary_key=True, nullable=False, comment="监测编码（主键）")
    station_code = Column(String(64), ForeignKey("hydro_station.station_code"), nullable=True, comment="测站编码（FK→hydro_station.station_code）")
    station_name = Column(String(255), nullable=True, comment="测站名称")
    monitor_time = Column(DateTime, nullable=True, comment="监测时间")
    water_level = Column(DECIMAL(14,4), nullable=True, comment="水位")
    traffic = Column(DECIMAL(14,4), nullable=True, comment="流量")
    rainfall = Column(DECIMAL(14,4), nullable=True, comment="雨量")
    tag_org_code = Column(String(64), nullable=True, comment="内部创建人所在组织编码")
    tag_supplier_code = Column(String(64), nullable=True, comment="外部创建人所属供应商编码")
    tag_creator_code = Column(String(64), nullable=True, comment="数据记录创建人编码")
    tag_reviser_code = Column(String(64), nullable=True, comment="数据记录最后修改人编码")
    tag_equip_code = Column(String(64), nullable=True, comment="数据采集设备编码")
    tag_station_code = Column(String(64), nullable=True, comment="数据采集监测站编码")
    tag_time_create = Column(DateTime, nullable=True, comment="数据记录创建或采集的时间")
    tag_time_update = Column(DateTime, nullable=True, comment="数据记录最后修改时间")
    tag_lon = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在经度(°)")
    tag_lat = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在纬度(°)")
    tag_alt = Column(DECIMAL(10,3), nullable=True, comment="数据采集设备所在海拔")
    tag_srs = Column(String(128), nullable=True, comment="CGCS2000,WGS84, 北京54，西安80")


class AutoSurfaceWaterStation(Base):
    """自动地表水水质测站信息表 (auto_surface_water_station)"""
    __tablename__ = "auto_surface_water_station"
    __table_args__ = {"comment": "自动地表水水质测站信息表"}

    station_code = Column(String(64), primary_key=True, nullable=False, comment="测站编码（主键）")
    station_name = Column(String(255), nullable=True, comment="测站名称")
    longitude = Column(DECIMAL(10,6), nullable=True, comment="经度（°）")
    latitude = Column(DECIMAL(10,6), nullable=True, comment="纬度（°）")
    altitude = Column(DECIMAL(10,3), nullable=True, comment="海拔")
    location = Column(String(255), nullable=True, comment="位置")
    monitor_river = Column(String(255), nullable=True, comment="监测河流")
    tag_org_code = Column(String(64), nullable=True, comment="内部创建人所在组织编码")
    tag_supplier_code = Column(String(64), nullable=True, comment="外部创建人所属供应商编码")
    tag_creator_code = Column(String(64), nullable=True, comment="数据记录创建人编码")
    tag_reviser_code = Column(String(64), nullable=True, comment="数据记录最后修改人编码")
    tag_equip_code = Column(String(64), nullable=True, comment="数据采集设备编码")
    tag_station_code = Column(String(64), nullable=True, comment="数据采集监测站编码")
    tag_time_create = Column(DateTime, nullable=True, comment="数据记录创建或采集的时间")
    tag_time_update = Column(DateTime, nullable=True, comment="数据记录最后修改时间")
    tag_lon = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在经度(°)")
    tag_lat = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在纬度(°)")
    tag_alt = Column(DECIMAL(10,3), nullable=True, comment="数据采集设备所在海拔")
    tag_srs = Column(String(128), nullable=True, comment="CGCS2000,WGS84, 北京54，西安80")


class AutoSurfaceWaterData(Base):
    """自动地表水水质监测数据表 (auto_surface_water_data)"""
    __tablename__ = "auto_surface_water_data"
    __table_args__ = {"comment": "自动地表水水质监测数据表"}

    monitor_code = Column(String(64), primary_key=True, nullable=False, comment="监测编码（主键）")
    station_code = Column(String(64), ForeignKey("auto_surface_water_station.station_code"), nullable=True, comment="测站编码（FK→auto_surface_water_station.station_code）")
    station_name = Column(String(255), nullable=True, comment="测站名称")
    monitor_time = Column(DateTime, nullable=True, comment="监测时间")
    wt = Column(DECIMAL(6,2), nullable=True, comment="水温")
    turb = Column(DECIMAL(14,4), nullable=True, comment="浊度")
    cond = Column(DECIMAL(14,4), nullable=True, comment="电导率")
    tn = Column(DECIMAL(14,4), nullable=True, comment="总氮")
    ph = Column(DECIMAL(5,2), nullable=True, comment="ph值")
    dox = Column(DECIMAL(14,4), nullable=True, comment="溶解氧")
    codmn = Column(DECIMAL(14,4), nullable=True, comment="高锰酸盐指数")
    nh3n = Column(DECIMAL(14,4), nullable=True, comment="氨氮")
    tp = Column(DECIMAL(14,4), nullable=True, comment="总磷")
    tag_org_code = Column(String(64), nullable=True, comment="内部创建人所在组织编码")
    tag_supplier_code = Column(String(64), nullable=True, comment="外部创建人所属供应商编码")
    tag_creator_code = Column(String(64), nullable=True, comment="数据记录创建人编码")
    tag_reviser_code = Column(String(64), nullable=True, comment="数据记录最后修改人编码")
    tag_equip_code = Column(String(64), nullable=True, comment="数据采集设备编码")
    tag_station_code = Column(String(64), nullable=True, comment="数据采集监测站编码")
    tag_time_create = Column(DateTime, nullable=True, comment="数据记录创建或采集的时间")
    tag_time_update = Column(DateTime, nullable=True, comment="数据记录最后修改时间")
    tag_lon = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在经度(°)")
    tag_lat = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在纬度(°)")
    tag_alt = Column(DECIMAL(10,3), nullable=True, comment="数据采集设备所在海拔")
    tag_srs = Column(String(128), nullable=True, comment="CGCS2000,WGS84, 北京54，西安80")


class ManualSurfaceWaterStation(Base):
    """人工地表水水质测站信息表 (manual_surface_water_station)"""
    __tablename__ = "manual_surface_water_station"
    __table_args__ = {"comment": "人工地表水水质测站信息表"}

    station_code = Column(String(64), primary_key=True, nullable=False, comment="测站编码（主键）")
    station_name = Column(String(255), nullable=True, comment="测站名称")
    longitude = Column(DECIMAL(10,6), nullable=True, comment="经度（°）")
    latitude = Column(DECIMAL(10,6), nullable=True, comment="纬度（°）")
    altitude = Column(DECIMAL(10,3), nullable=True, comment="海拔")
    location = Column(String(255), nullable=True, comment="位置")
    tag_org_code = Column(String(64), nullable=True, comment="内部创建人所在组织编码")
    tag_supplier_code = Column(String(64), nullable=True, comment="外部创建人所属供应商编码")
    tag_creator_code = Column(String(64), nullable=True, comment="数据记录创建人编码")
    tag_reviser_code = Column(String(64), nullable=True, comment="数据记录最后修改人编码")
    tag_equip_code = Column(String(64), nullable=True, comment="数据采集设备编码")
    tag_station_code = Column(String(64), nullable=True, comment="数据采集监测站编码")
    tag_time_create = Column(DateTime, nullable=True, comment="数据记录创建或采集的时间")
    tag_time_update = Column(DateTime, nullable=True, comment="数据记录最后修改时间")
    tag_lon = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在经度(°)")
    tag_lat = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在纬度(°)")
    tag_alt = Column(DECIMAL(10,3), nullable=True, comment="数据采集设备所在海拔")
    tag_srs = Column(String(128), nullable=True, comment="CGCS2000,WGS84, 北京54，西安80")


class ManualSurfaceWaterData(Base):
    """人工地表水水质监测数据表 (manual_surface_water_data)"""
    __tablename__ = "manual_surface_water_data"
    __table_args__ = {"comment": "人工地表水水质监测数据表"}

    monitor_code = Column(String(64), primary_key=True, nullable=False, comment="监测编码（主键）")
    station_code = Column(String(64), ForeignKey("manual_surface_water_station.station_code"), nullable=True, comment="测站编码（FK→manual_surface_water_station.station_code）")
    station_name = Column(String(255), nullable=True, comment="测站名称")
    monitor_time = Column(DateTime, nullable=True, comment="监测时间")
    wt = Column(DECIMAL(6,2), nullable=True, comment="水温")
    ph = Column(DECIMAL(5,2), nullable=True, comment="ph值")
    dox = Column(DECIMAL(14,4), nullable=True, comment="溶解氧")
    codmn = Column(DECIMAL(14,4), nullable=True, comment="高锰酸盐指数")
    codcr = Column(DECIMAL(14,4), nullable=True, comment="化学需氧量")
    bod5 = Column(DECIMAL(14,4), nullable=True, comment="五日生化需氧量")
    nh3n = Column(DECIMAL(14,4), nullable=True, comment="氨氮")
    oil = Column(DECIMAL(14,4), nullable=True, comment="石油类")
    vlph = Column(DECIMAL(14,4), nullable=True, comment="挥发酚")
    hg = Column(DECIMAL(14,4), nullable=True, comment="汞")
    pb = Column(DECIMAL(14,4), nullable=True, comment="铅")
    tn = Column(DECIMAL(14,4), nullable=True, comment="总氮")
    tp = Column(DECIMAL(14,4), nullable=True, comment="总磷")
    cu = Column(DECIMAL(14,4), nullable=True, comment="铜")
    zn = Column(DECIMAL(14,4), nullable=True, comment="锌")
    f = Column(DECIMAL(14,4), nullable=True, comment="氟化物")
    se = Column(DECIMAL(14,4), nullable=True, comment="硒")
    ars = Column("as", DECIMAL(14,4), nullable=True, comment="砷")
    cd = Column(DECIMAL(14,4), nullable=True, comment="镉")
    cn = Column(DECIMAL(14,4), nullable=True, comment="氰化物")
    las = Column(DECIMAL(14,4), nullable=True, comment="阴离子表面活性剂")
    s2 = Column(DECIMAL(14,4), nullable=True, comment="硫化物")
    fcg = Column(DECIMAL(14,4), nullable=True, comment="粪大肠菌群")
    ss = Column(DECIMAL(14,4), nullable=True, comment="悬浮物")
    ll = Column(DECIMAL(14,4), nullable=True, comment="流量")
    cond = Column(DECIMAL(14,4), nullable=True, comment="电导率")
    sulfate = Column(DECIMAL(14,4), nullable=True, comment="硫酸盐")
    chloride = Column(DECIMAL(14,4), nullable=True, comment="氯化物")
    nitrate = Column(DECIMAL(14,4), nullable=True, comment="硝酸盐")
    fe = Column(DECIMAL(14,4), nullable=True, comment="铁")
    mn = Column(DECIMAL(14,4), nullable=True, comment="锰")
    tag_org_code = Column(String(64), nullable=True, comment="内部创建人所在组织编码")
    tag_supplier_code = Column(String(64), nullable=True, comment="外部创建人所属供应商编码")
    tag_creator_code = Column(String(64), nullable=True, comment="数据记录创建人编码")
    tag_reviser_code = Column(String(64), nullable=True, comment="数据记录最后修改人编码")
    tag_equip_code = Column(String(64), nullable=True, comment="数据采集设备编码")
    tag_station_code = Column(String(64), nullable=True, comment="数据采集监测站编码")
    tag_time_create = Column(DateTime, nullable=True, comment="数据记录创建或采集的时间")
    tag_time_update = Column(DateTime, nullable=True, comment="数据记录最后修改时间")
    tag_lon = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在经度(°)")
    tag_lat = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在纬度(°)")
    tag_alt = Column(DECIMAL(10,3), nullable=True, comment="数据采集设备所在海拔")
    tag_srs = Column(String(128), nullable=True, comment="CGCS2000,WGS84, 北京54，西安80")


class SedimentStation(Base):
    """沉积物测站信息表 (sediment_station)"""
    __tablename__ = "sediment_station"
    __table_args__ = {"comment": "沉积物测站信息表"}

    station_code = Column(String(64), primary_key=True, nullable=False, comment="测站编码（主键）")
    station_name = Column(String(255), nullable=True, comment="测站名称")
    longitude = Column(DECIMAL(10,6), nullable=True, comment="经度（°）")
    latitude = Column(DECIMAL(10,6), nullable=True, comment="纬度（°）")
    altitude = Column(DECIMAL(10,3), nullable=True, comment="海拔")
    location = Column(String(255), nullable=True, comment="位置")
    tag_org_code = Column(String(64), nullable=True, comment="内部创建人所在组织编码")
    tag_supplier_code = Column(String(64), nullable=True, comment="外部创建人所属供应商编码")
    tag_creator_code = Column(String(64), nullable=True, comment="数据记录创建人编码")
    tag_reviser_code = Column(String(64), nullable=True, comment="数据记录最后修改人编码")
    tag_equip_code = Column(String(64), nullable=True, comment="数据采集设备编码")
    tag_station_code = Column(String(64), nullable=True, comment="数据采集监测站编码")
    tag_time_create = Column(DateTime, nullable=True, comment="数据记录创建或采集的时间")
    tag_time_update = Column(DateTime, nullable=True, comment="数据记录最后修改时间")
    tag_lon = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在经度(°)")
    tag_lat = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在纬度(°)")
    tag_alt = Column(DECIMAL(10,3), nullable=True, comment="数据采集设备所在海拔")
    tag_srs = Column(String(128), nullable=True, comment="CGCS2000,WGS84, 北京54，西安80")


class SedimentData(Base):
    """沉积物监测数据表 (sediment_data)"""
    __tablename__ = "sediment_data"
    __table_args__ = {"comment": "沉积物监测数据表"}

    monitor_code = Column(String(64), primary_key=True, nullable=False, comment="监测编码（主键）")
    station_code = Column(String(64), ForeignKey("sediment_station.station_code"), nullable=True, comment="测站编码（FK→sediment_station.station_code）")
    station_name = Column(String(255), nullable=True, comment="测站名称")
    monitor_time = Column(DateTime, nullable=True, comment="监测时间")
    alpha_hch = Column(DECIMAL(14,4), nullable=True, comment="α-HCH")
    beta_hch = Column(DECIMAL(14,4), nullable=True, comment="β-HCH")
    gamma_hch = Column(DECIMAL(14,4), nullable=True, comment="γ-HCH")
    delta_hch = Column(DECIMAL(14,4), nullable=True, comment="δ-HCH")
    dde_4_4 = Column(DECIMAL(14,4), nullable=True, comment="4,4'-DDE")
    ddd_4_4 = Column(DECIMAL(14,4), nullable=True, comment="4,4'-DDD")
    ddt_2_4 = Column(DECIMAL(14,4), nullable=True, comment="2,4'-DDT")
    ddt_4_4 = Column(DECIMAL(14,4), nullable=True, comment="4,4'-DDT")
    c10h8 = Column(DECIMAL(14,4), nullable=True, comment="萘")
    c12h8 = Column(DECIMAL(14,4), nullable=True, comment="苊烯")
    c12h10 = Column(DECIMAL(14,4), nullable=True, comment="苊")
    c13h10 = Column(DECIMAL(14,4), nullable=True, comment="芴")
    c14h10_fei = Column(DECIMAL(14,4), nullable=True, comment="菲")
    c14h10_en = Column(DECIMAL(14,4), nullable=True, comment="蒽")
    c16h10_yingen = Column(DECIMAL(14,4), nullable=True, comment="荧蒽")
    c16h10_p = Column(DECIMAL(14,4), nullable=True, comment="芘")
    c18d12 = Column(DECIMAL(14,4), nullable=True, comment="苯并[a]蒽")
    c18h12 = Column(DECIMAL(14,4), nullable=True, comment="屈")
    c20h12_b = Column(DECIMAL(14,4), nullable=True, comment="苯并[b]荧蒽")
    c20h12_k = Column(DECIMAL(14,4), nullable=True, comment="苯并[k]荧蒽")
    c20h12_a = Column(DECIMAL(14,4), nullable=True, comment="苯并[a]芘")
    c22h12_1_2_3_cd = Column(DECIMAL(14,4), nullable=True, comment="茚并[1,2,3-cd]芘")
    c22h14 = Column(DECIMAL(14,4), nullable=True, comment="二苯并[a,h]蒽")
    c22h12_g_h_i = Column(DECIMAL(14,4), nullable=True, comment="苯并[g,h,i]苝")
    c4h7cl2o4p = Column(DECIMAL(14,4), nullable=True, comment="敌敌畏")
    c7h13o6p = Column(DECIMAL(14,4), nullable=True, comment="蝇毒磷")
    c8h13n2o3ps = Column(DECIMAL(14,4), nullable=True, comment="吡唑硫磷")
    c8h19o3ps2_o = Column(DECIMAL(14,4), nullable=True, comment="溴苯磷")
    c8h19o2ps2 = Column(DECIMAL(14,4), nullable=True, comment="溴螨酯")
    c8h20o5p2s2 = Column(DECIMAL(14,4), nullable=True, comment="苯硫磷")
    c7h17o2ps3 = Column(DECIMAL(14,4), nullable=True, comment="增效醚")
    c8h19o3ps2_s = Column(DECIMAL(14,4), nullable=True, comment="硫丹硫酸酯")
    c5h12no3ps2 = Column(DECIMAL(14,4), nullable=True, comment="三硫磷")
    c12h21n2o3ps = Column(DECIMAL(14,4), nullable=True, comment="倍硫磷砜")
    c8h19o2ps3 = Column(DECIMAL(14,4), nullable=True, comment="丰索磷")
    c6h12no4ps2 = Column(DECIMAL(14,4), nullable=True, comment="脱叶亚磷")
    c8h10no5ps = Column(DECIMAL(14,4), nullable=True, comment="丙硫磷")
    pml = Column(DECIMAL(14,4), nullable=True, comment="杀虫畏")
    c10h19o6ps2 = Column(DECIMAL(14,4), nullable=True, comment="地胺磷")
    c9h11cl3no3ps = Column(DECIMAL(14,4), nullable=True, comment="灭蚜磷")
    c7h17o4ps3 = Column(DECIMAL(14,4), nullable=True, comment="氟虫腈")
    c10h15o3ps2 = Column(DECIMAL(14,4), nullable=True, comment="毒壤磷")
    c10h14no5ps = Column(DECIMAL(14,4), nullable=True, comment="育畜磷")
    c14h16cln3o2 = Column(DECIMAL(14,4), nullable=True, comment="粉锈宁")
    c12h19clno3p = Column(DECIMAL(14,4), nullable=True, comment="对硫磷")
    c10h12cl3o2ps = Column(DECIMAL(14,4), nullable=True, comment="倍硫磷")
    c12h4cl2f6n4os = Column(DECIMAL(14,4), nullable=True, comment="甲拌磷砜")
    c10h20no5ps2 = Column(DECIMAL(14,4), nullable=True, comment="毒死蜱")
    c8h16no3ps2 = Column(DECIMAL(14,4), nullable=True, comment="马拉硫磷")
    c10h9cl4o4p = Column(DECIMAL(14,4), nullable=True, comment="皮螟磷")
    c11h15cl2o2ps2 = Column(DECIMAL(14,4), nullable=True, comment="甲基对硫磷")
    c12h27ps3 = Column(DECIMAL(14,4), nullable=True, comment="安硫磷")
    c11h17o4ps2 = Column(DECIMAL(14,4), nullable=True, comment="乙拌磷")
    c10h15o6ps = Column(DECIMAL(14,4), nullable=True, comment="二嗪农")
    c11h16clo2ps3 = Column(DECIMAL(14,4), nullable=True, comment="乐果")
    c9h6cl6o4s = Column(DECIMAL(14,4), nullable=True, comment="内吸磷(S)")
    c19h30o5 = Column(DECIMAL(14,4), nullable=True, comment="甲拌磷")
    c14h14no4ps = Column(DECIMAL(14,4), nullable=True, comment="治螟磷")
    c17h16br2o3 = Column(DECIMAL(14,4), nullable=True, comment="灭克磷")
    c13h10brcl2o2ps = Column(DECIMAL(14,4), nullable=True, comment="内吸磷(O)")
    c14h18cln2o3ps = Column(DECIMAL(14,4), nullable=True, comment="虫线磷")
    c14h16clo5ps = Column(DECIMAL(14,4), nullable=True, comment="速灭磷")
    ch3cl = Column(DECIMAL(14,4), nullable=True, comment="氯甲烷")
    c2h3cl = Column(DECIMAL(14,4), nullable=True, comment="氯乙烯")
    c2h2cl2 = Column(DECIMAL(14,4), nullable=True, comment="1,1-二氯乙烯")
    ch2cl2 = Column(DECIMAL(14,4), nullable=True, comment="二氯甲烷")
    f_c2h2cl2 = Column(DECIMAL(14,4), nullable=True, comment="反式-1,2-二氯乙烯")
    c2h4cl2_1_1 = Column(DECIMAL(14,4), nullable=True, comment="1,1-二氯乙烷")
    s_c2h2cl2 = Column(DECIMAL(14,4), nullable=True, comment="顺式-1,2-二氯乙烯")
    chcl3 = Column(DECIMAL(14,4), nullable=True, comment="氯仿")
    c2h3cl3_1_1_1 = Column(DECIMAL(14,4), nullable=True, comment="1,1,1-三氯乙烷")
    ccl4 = Column(DECIMAL(14,4), nullable=True, comment="四氯化碳")
    c6h6 = Column(DECIMAL(14,4), nullable=True, comment="苯")
    c2h4cl2_1_2 = Column(DECIMAL(14,4), nullable=True, comment="1,2-二氯乙烷")
    c2hcl3 = Column(DECIMAL(14,4), nullable=True, comment="三氯乙烯")
    c3h6cl2 = Column(DECIMAL(14,4), nullable=True, comment="1,2-二氯丙烷")
    c7h8 = Column(DECIMAL(14,4), nullable=True, comment="甲苯")
    c2h3cl3_1_1_2 = Column(DECIMAL(14,4), nullable=True, comment="1,1,2-三氯乙烷")
    c2cl4 = Column(DECIMAL(14,4), nullable=True, comment="四氯乙烯")
    c6h5cl = Column(DECIMAL(14,4), nullable=True, comment="氯苯")
    c2h2cl4_1_1_1_2 = Column(DECIMAL(14,4), nullable=True, comment="1,1,1,2-四氯乙烷")
    c8h10 = Column(DECIMAL(14,4), nullable=True, comment="乙苯")
    j_d_c8h10 = Column(DECIMAL(14,4), nullable=True, comment="间+对二甲苯")
    l_c8h10 = Column(DECIMAL(14,4), nullable=True, comment="邻二甲苯")
    c8h8 = Column(DECIMAL(14,4), nullable=True, comment="苯乙烯")
    c2h2cl4_1_1_2_2 = Column(DECIMAL(14,4), nullable=True, comment="1,1,2,2-四氯乙烷")
    c3h5cl3 = Column(DECIMAL(14,4), nullable=True, comment="1,2,3-三氯丙烷")
    c6h4cl2_1_4 = Column(DECIMAL(14,4), nullable=True, comment="1,4-二氯苯")
    c6h4cl2_1_2 = Column(DECIMAL(14,4), nullable=True, comment="1,2-二氯苯")
    tag_org_code = Column(String(64), nullable=True, comment="内部创建人所在组织编码")
    tag_supplier_code = Column(String(64), nullable=True, comment="外部创建人所属供应商编码")
    tag_creator_code = Column(String(64), nullable=True, comment="数据记录创建人编码")
    tag_reviser_code = Column(String(64), nullable=True, comment="数据记录最后修改人编码")
    tag_equip_code = Column(String(64), nullable=True, comment="数据采集设备编码")
    tag_station_code = Column(String(64), nullable=True, comment="数据采集监测站编码")
    tag_time_create = Column(DateTime, nullable=True, comment="数据记录创建或采集的时间")
    tag_time_update = Column(DateTime, nullable=True, comment="数据记录最后修改时间")
    tag_lon = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在经度(°)")
    tag_lat = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在纬度(°)")
    tag_alt = Column(DECIMAL(10,3), nullable=True, comment="数据采集设备所在海拔")
    tag_srs = Column(String(128), nullable=True, comment="CGCS2000,WGS84, 北京54，西安80")


class AutoWaterTempStation(Base):
    """自动水温测站信息表 (auto_water_temp_station)"""
    __tablename__ = "auto_water_temp_station"
    __table_args__ = {"comment": "自动水温测站信息表"}

    station_code = Column(String(64), primary_key=True, nullable=False, comment="测站编码（主键）")
    station_name = Column(String(255), nullable=True, comment="测站名称")
    longitude = Column(DECIMAL(10,6), nullable=True, comment="经度（°）")
    latitude = Column(DECIMAL(10,6), nullable=True, comment="纬度（°）")
    altitude = Column(DECIMAL(10,3), nullable=True, comment="海拔")
    location = Column(String(255), nullable=True, comment="位置")
    tag_org_code = Column(String(64), nullable=True, comment="内部创建人所在组织编码")
    tag_supplier_code = Column(String(64), nullable=True, comment="外部创建人所属供应商编码")
    tag_creator_code = Column(String(64), nullable=True, comment="数据记录创建人编码")
    tag_reviser_code = Column(String(64), nullable=True, comment="数据记录最后修改人编码")
    tag_equip_code = Column(String(64), nullable=True, comment="数据采集设备编码")
    tag_station_code = Column(String(64), nullable=True, comment="数据采集监测站编码")
    tag_time_create = Column(DateTime, nullable=True, comment="数据记录创建或采集的时间")
    tag_time_update = Column(DateTime, nullable=True, comment="数据记录最后修改时间")
    tag_lon = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在经度(°)")
    tag_lat = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在纬度(°)")
    tag_alt = Column(DECIMAL(10,3), nullable=True, comment="数据采集设备所在海拔")
    tag_srs = Column(String(128), nullable=True, comment="CGCS2000,WGS84, 北京54，西安80")


class AutoWaterTempData(Base):
    """自动水温监测数据表 (auto_water_temp_data)"""
    __tablename__ = "auto_water_temp_data"
    __table_args__ = {"comment": "自动水温监测数据表"}

    monitor_code = Column(String(64), primary_key=True, nullable=False, comment="监测编码（主键）")
    station_code = Column(String(64), ForeignKey("auto_water_temp_station.station_code"), nullable=True, comment="测站编码（FK→auto_water_temp_station.station_code）")
    station_name = Column(String(255), nullable=True, comment="测站名称")
    monitor_time = Column(DateTime, nullable=True, comment="监测时间")
    cond = Column(DECIMAL(14,4), nullable=True, comment="电导率")
    wt = Column(DECIMAL(6,2), nullable=True, comment="水温")


class AutoGroundwaterLevelStation(Base):
    """自动地下水水位测站信息表 (auto_groundwater_level_station)"""
    __tablename__ = "auto_groundwater_level_station"
    __table_args__ = {"comment": "自动地下水水位测站信息表"}

    station_code = Column(String(64), primary_key=True, nullable=False, comment="测站编码（主键）")
    station_name = Column(String(255), nullable=True, comment="测站名称")
    longitude = Column(DECIMAL(10,6), nullable=True, comment="经度（°）")
    latitude = Column(DECIMAL(10,6), nullable=True, comment="纬度（°）")
    altitude = Column(DECIMAL(10,3), nullable=True, comment="海拔")
    location = Column(String(255), nullable=True, comment="位置")
    tag_org_code = Column(String(64), nullable=True, comment="内部创建人所在组织编码")
    tag_supplier_code = Column(String(64), nullable=True, comment="外部创建人所属供应商编码")
    tag_creator_code = Column(String(64), nullable=True, comment="数据记录创建人编码")
    tag_reviser_code = Column(String(64), nullable=True, comment="数据记录最后修改人编码")
    tag_equip_code = Column(String(64), nullable=True, comment="数据采集设备编码")
    tag_station_code = Column(String(64), nullable=True, comment="数据采集监测站编码")
    tag_time_create = Column(DateTime, nullable=True, comment="数据记录创建或采集的时间")
    tag_time_update = Column(DateTime, nullable=True, comment="数据记录最后修改时间")
    tag_lon = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在经度(°)")
    tag_lat = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在纬度(°)")
    tag_alt = Column(DECIMAL(10,3), nullable=True, comment="数据采集设备所在海拔")
    tag_srs = Column(String(128), nullable=True, comment="CGCS2000,WGS84, 北京54，西安80")


class AutoGroundwaterLevelData(Base):
    """自动地下水水位监测数据表 (auto_groundwater_level_data)"""
    __tablename__ = "auto_groundwater_level_data"
    __table_args__ = {"comment": "自动地下水水位监测数据表"}

    monitor_code = Column(String(64), primary_key=True, nullable=False, comment="监测编码（主键）")
    station_code = Column(String(64), ForeignKey("auto_groundwater_level_station.station_code"), nullable=True, comment="测站编码（FK→auto_groundwater_level_station.station_code）")
    station_name = Column(String(255), nullable=True, comment="测站名称")
    monitor_time = Column(DateTime, nullable=True, comment="监测时间")
    water_level = Column(DECIMAL(14,4), nullable=True, comment="水位")
    bd = Column(DECIMAL(14,4), nullable=True, comment="埋深")
    elevation = Column(DECIMAL(14,4), nullable=True, comment="水位标高")
    depth = Column(DECIMAL(14,4), nullable=True, comment="水位埋深")
    cond = Column(DECIMAL(14,4), nullable=True, comment="电导率")
    wt = Column(DECIMAL(6,2), nullable=True, comment="水温")


class ManualGroundwaterQualityStation(Base):
    """人工地下水水质测站信息表 (manual_groundwater_quality_station)"""
    __tablename__ = "manual_groundwater_quality_station"
    __table_args__ = {"comment": "人工地下水水质测站信息表"}

    station_code = Column(String(64), primary_key=True, nullable=False, comment="测站编码（主键）")
    station_name = Column(String(255), nullable=True, comment="测站名称")
    longitude = Column(DECIMAL(10,6), nullable=True, comment="经度（°）")
    latitude = Column(DECIMAL(10,6), nullable=True, comment="纬度（°）")
    altitude = Column(DECIMAL(10,3), nullable=True, comment="海拔")
    location = Column(String(255), nullable=True, comment="位置")
    tag_org_code = Column(String(64), nullable=True, comment="内部创建人所在组织编码")
    tag_supplier_code = Column(String(64), nullable=True, comment="外部创建人所属供应商编码")
    tag_creator_code = Column(String(64), nullable=True, comment="数据记录创建人编码")
    tag_reviser_code = Column(String(64), nullable=True, comment="数据记录最后修改人编码")
    tag_equip_code = Column(String(64), nullable=True, comment="数据采集设备编码")
    tag_station_code = Column(String(64), nullable=True, comment="数据采集监测站编码")
    tag_time_create = Column(DateTime, nullable=True, comment="数据记录创建或采集的时间")
    tag_time_update = Column(DateTime, nullable=True, comment="数据记录最后修改时间")
    tag_lon = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在经度(°)")
    tag_lat = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在纬度(°)")
    tag_alt = Column(DECIMAL(10,3), nullable=True, comment="数据采集设备所在海拔")
    tag_srs = Column(String(128), nullable=True, comment="CGCS2000,WGS84, 北京54，西安80")


class ManualGroundwaterQualityData(Base):
    """人工地下水水质监测数据表 (manual_groundwater_quality_data)"""
    __tablename__ = "manual_groundwater_quality_data"
    __table_args__ = {"comment": "人工地下水水质监测数据表"}

    monitor_code = Column(String(64), primary_key=True, nullable=False, comment="监测编码（主键）")
    station_code = Column(String(64), ForeignKey("manual_groundwater_quality_station.station_code"), nullable=True, comment="测站编码（FK→manual_groundwater_quality_station.station_code）")
    station_name = Column(String(255), nullable=True, comment="测站名称")
    monitor_time = Column(DateTime, nullable=True, comment="监测时间")
    spdeepth = Column(DECIMAL(14,4), nullable=True, comment="采样深度")
    ph = Column(DECIMAL(5,2), nullable=True, comment="pH")
    nh3n = Column(DECIMAL(14,4), nullable=True, comment="氨氮")
    nitrate = Column(DECIMAL(14,4), nullable=True, comment="硝酸盐")
    nitrite = Column(DECIMAL(14,4), nullable=True, comment="亚硝酸盐")
    vlph = Column(DECIMAL(14,4), nullable=True, comment="挥发性酚类")
    cn = Column(DECIMAL(14,4), nullable=True, comment="氰化物")
    ars = Column(DECIMAL(14,4), nullable=True, comment="砷")
    hg = Column(DECIMAL(14,4), nullable=True, comment="汞")
    cr6 = Column(DECIMAL(14,4), nullable=True, comment="六价铬")
    thrd = Column(DECIMAL(14,4), nullable=True, comment="总硬度")
    pb = Column(DECIMAL(14,4), nullable=True, comment="铅")
    f = Column(DECIMAL(14,4), nullable=True, comment="氟化物")
    cd = Column(DECIMAL(14,4), nullable=True, comment="镉")
    fe = Column(DECIMAL(14,4), nullable=True, comment="铁")
    mn = Column(DECIMAL(14,4), nullable=True, comment="锰")
    tds = Column(DECIMAL(14,4), nullable=True, comment="溶解性总固体")
    codmn = Column(DECIMAL(14,4), nullable=True, comment="高锰酸钾指数")
    sulfate = Column(DECIMAL(14,4), nullable=True, comment="硫酸盐")
    cl = Column(DECIMAL(14,4), nullable=True, comment="氯化物")
    fcg = Column(DECIMAL(14,4), nullable=True, comment="粪大肠菌群")
    bctc = Column(DECIMAL(14,4), nullable=True, comment="细菌总数")
    wt = Column(DECIMAL(6,2), nullable=True, comment="水温")
    cond = Column(DECIMAL(14,4), nullable=True, comment="电导率")
    turb = Column(DECIMAL(14,4), nullable=True, comment="浑浊度")
    chcl3 = Column(DECIMAL(14,4), nullable=True, comment="三氯甲烷")
    ccl4 = Column(DECIMAL(14,4), nullable=True, comment="四氯化碳")
    c6h6 = Column(DECIMAL(14,4), nullable=True, comment="苯")
    c7h8 = Column(DECIMAL(14,4), nullable=True, comment="甲苯")
    se = Column(DECIMAL(14,4), nullable=True, comment="硒")
    cu = Column(DECIMAL(14,4), nullable=True, comment="铜")
    zn = Column(DECIMAL(14,4), nullable=True, comment="锌")
    al = Column(DECIMAL(14,4), nullable=True, comment="铝")
    na = Column(DECIMAL(14,4), nullable=True, comment="钠")
    s2 = Column(DECIMAL(14,4), nullable=True, comment="硫化物")
    las = Column(DECIMAL(14,4), nullable=True, comment="阴离子表面活性剂")
    sd = Column(DECIMAL(14,4), nullable=True, comment="色度")
    i = Column(DECIMAL(14,4), nullable=True, comment="碘化物")
    alpha = Column(DECIMAL(14,4), nullable=True, comment="总α放射性")
    beta = Column(DECIMAL(14,4), nullable=True, comment="总β放射性")
    mg = Column(DECIMAL(14,4), nullable=True, comment="镁")
    k = Column(DECIMAL(14,4), nullable=True, comment="钾")
    ca = Column(DECIMAL(14,4), nullable=True, comment="钙")
    mo = Column(DECIMAL(14,4), nullable=True, comment="钼")
    co = Column(DECIMAL(14,4), nullable=True, comment="钴")
    be = Column(DECIMAL(14,4), nullable=True, comment="铍")
    sb = Column(DECIMAL(14,4), nullable=True, comment="锑")
    ba = Column(DECIMAL(14,4), nullable=True, comment="钡")
    v = Column(DECIMAL(14,4), nullable=True, comment="钒")
    tl = Column(DECIMAL(14,4), nullable=True, comment="铊")
    ti = Column(DECIMAL(14,4), nullable=True, comment="钛")
    cr = Column(DECIMAL(14,4), nullable=True, comment="铬")
    tag_org_code = Column(String(64), nullable=True, comment="内部创建人所在组织编码")
    tag_supplier_code = Column(String(64), nullable=True, comment="外部创建人所属供应商编码")
    tag_creator_code = Column(String(64), nullable=True, comment="数据记录创建人编码")
    tag_reviser_code = Column(String(64), nullable=True, comment="数据记录最后修改人编码")
    tag_equip_code = Column(String(64), nullable=True, comment="数据采集设备编码")
    tag_station_code = Column(String(64), nullable=True, comment="数据采集监测站编码")
    tag_time_create = Column(DateTime, nullable=True, comment="数据记录创建或采集的时间")
    tag_time_update = Column(DateTime, nullable=True, comment="数据记录最后修改时间")
    tag_lon = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在经度(°)")
    tag_lat = Column(DECIMAL(10,6), nullable=True, comment="数据采集设备所在纬度(°)")
    tag_alt = Column(DECIMAL(10,3), nullable=True, comment="数据采集设备所在海拔")
    tag_srs = Column(String(128), nullable=True, comment="CGCS2000,WGS84, 北京54，西安80")
